// Libellés de métiers traduits (générés). Clés = id de professions.ts.
// Le français est la source (professions.ts) ; ici en/de/es/zh.
import type { Lang } from './i18n'

export const PROFESSION_LABELS: Partial<Record<Lang, Record<string, string>>> = {
  en: {
    'data-entry': 'Data Entry Operator',
    'developer': 'Software Developer',
    'frontend-dev': 'Front-End Developer',
    'backend-dev': 'Back-End Developer',
    'fullstack-dev': 'Full-Stack Developer',
    'mobile-dev': 'Mobile Developer',
    'devops': 'DevOps Engineer',
    'data-scientist': 'Data Scientist',
    'data-analyst': 'Data Analyst',
    'data-engineer': 'Data Engineer',
    'ml-engineer': 'Machine Learning Engineer',
    'prompt-engineer': 'Prompt Engineer / AI Specialist',
    'cybersecurity': 'Cybersecurity Expert',
    'qa-tester': 'QA Tester',
    'it-support': 'IT Support Technician',
    'sysadmin': 'Systems & Network Administrator',
    'cloud-architect': 'Cloud Architect',
    'game-developer': 'Game Developer',
    'doctor': 'General Practitioner',
    'surgeon': 'Surgeon',
    'radiologist': 'Radiologist',
    'anesthetist': 'Anesthesiologist',
    'dentist': 'Dentist',
    'nurse': 'Nurse',
    'caregiver': 'Nursing Assistant',
    'midwife': 'Midwife',
    'physio': 'Physiotherapist',
    'psychologist': 'Psychologist',
    'psychiatrist': 'Psychiatrist',
    'pharmacist': 'Pharmacist',
    'pharmacy-tech': 'Pharmacy Technician',
    'vet': 'Veterinarian',
    'optician': 'Optician',
    'speech-therapist': 'Speech Therapist',
    'dietitian': 'Dietitian / Nutritionist',
    'paramedic': 'Paramedic',
    'social-worker': 'Social Worker',
    'teacher': 'Teacher',
    'primary-teacher': 'Primary School Teacher',
    'professor': 'University Professor',
    'trainer': 'Professional Trainer',
    'researcher': 'Researcher / Scientist',
    'career-advisor': 'Career Counselor',
    'librarian': 'Librarian',
    'graphic-designer': 'Graphic Designer',
    'ux-designer': 'UX Designer',
    'ui-designer': 'UI Designer',
    'motion-designer': 'Motion Designer',
    'illustrator': 'Illustrator',
    'product-designer': 'Product Designer',
    'interior-designer': 'Interior Designer',
    'architect': 'Architect',
    'photographer': 'Photographer',
    'video-editor': 'Video Editor',
    'writer': 'Writer / Journalist',
    'translator': 'Translator / Interpreter',
    'screenwriter': 'Screenwriter',
    'musician': 'Musician / Composer',
    'accountant': 'Accountant',
    'chartered-accountant': 'Chartered Accountant',
    'controller': 'Management Controller',
    'auditor': 'Auditor',
    'tax-advisor': 'Tax Advisor',
    'financial-analyst': 'Financial Analyst',
    'trader': 'Trader',
    'wealth-manager': 'Wealth Manager',
    'actuary': 'Actuary',
    'lawyer': 'Lawyer',
    'jurist': 'Corporate Counsel',
    'notary': 'Notary',
    'magistrate': 'Magistrate / Judge',
    'bank-teller': 'Bank Advisor',
    'insurer': 'Insurance Advisor',
    'sales': 'Sales Representative',
    'b2b-sales': 'B2B / Key Account Sales',
    'marketing': 'Marketing Manager',
    'product-marketing': 'Product Manager',
    'growth-marketer': 'Growth Marketer',
    'seo-specialist': 'SEO / SEA Specialist',
    'social-media': 'Community / Social Media Manager',
    'buyer': 'Buyer',
    'ecommerce-manager': 'E-commerce Manager',
    'pr': 'Press Officer / Public Relations',
    'shop-assistant': 'Sales Assistant',
    'cashier': 'Cashier',
    'customer-support': 'Customer Service Advisor',
    'manager': 'Manager / Team Lead',
    'ceo': 'CEO',
    'cfo': 'Chief Financial Officer',
    'project-manager': 'Project Manager',
    'product-manager': 'Product Manager',
    'consultant': 'Strategy Consultant',
    'hr': 'HR Manager',
    'recruiter': 'Recruiter',
    'exec-assistant': 'Executive Assistant',
    'entrepreneur': 'Entrepreneur',
    'driver': 'Driver / Delivery Driver',
    'factory-worker': 'Production Operator',
    'logistics': 'Logistics Clerk / Warehouse Operative',
    'maintenance-tech': 'Maintenance Technician',
    'production-engineer': 'Production Engineer',
    'welder': 'Welder',
    'cnc-operator': 'CNC Machinist',
    'pilot': 'Airline Pilot',
    'air-traffic': 'Air Traffic Controller',
    'train-driver': 'Train Driver',
    'site-manager': 'Site Manager',
    'supply-chain': 'Supply Chain Manager',
    'electrician': 'Electrician',
    'plumber': 'Plumber / Heating Engineer',
    'carpenter': 'Carpenter / Joiner',
    'mason': 'Mason',
    'painter': 'Painter and Decorator',
    'roofer': 'Roofer',
    'chef': 'Chef',
    'baker': 'Baker',
    'pastry-chef': 'Pastry Chef',
    'butcher': 'Butcher',
    'hairdresser': 'Hairdresser',
    'beautician': 'Beautician',
    'mechanic': 'Auto Mechanic',
    'landscaper': 'Landscaper / Gardener',
    'farmer': 'Farmer',
    'tailor': 'Tailor',
    'police': 'Police Officer',
    'firefighter': 'Firefighter',
    'soldier': 'Soldier',
    'civil-servant': 'Civil Servant',
    'receptionist': 'Receptionist',
    'flight-attendant': 'Flight Attendant',
    'real-estate': 'Real Estate Agent',
    'waiter': 'Waiter',
    'bartender': 'Bartender',
    'tour-guide': 'Tour Guide',
    'sports-coach': 'Sports Coach',
    'childcare': 'Childcare Assistant',
    'cleaner': 'Cleaner',
    'security-guard': 'Security Guard',
    'comms-manager': 'Communications Officer',
    'web-writer': 'Web Content Writer / Content Manager',
    'presenter': 'Presenter / Host',
    'civil-engineer': 'Civil Engineer',
    'mechanical-engineer': 'Mechanical Engineer',
    'electrical-engineer': 'Electrical Engineer',
    'chemist': 'Chemist',
    'biologist': 'Biologist',
    'env-engineer': 'Environmental Engineer',
    'statistician': 'Statistician',
    'economist': 'Economist',
    'surveyor': 'Surveyor',
    'urban-planner': 'Urban Planner',
    'lab-technician': 'Lab Technician',
    'meteorologist': 'Meteorologist',
    'dpo': 'Data Protection Officer (DPO)',
    'actor': 'Actor',
    'dancer': 'Dancer',
    'sound-engineer': 'Sound Engineer',
    'film-director': 'Film Director / Producer',
    'event-manager': 'Event Manager',
    'makeup-artist': 'Makeup Artist',
    'bus-driver': 'Bus Driver',
    'postal-worker': 'Postal Worker',
    'waste-collector': 'Refuse collector',
    'travel-agent': 'Travel agent',
    'florist': 'Florist',
    'watchmaker': 'Watchmaker',
    'locksmith': 'Locksmith',
    'mover': 'Mover',
    'fishmonger': 'Fishmonger',
    'scrum-master': 'Scrum Master / Agile Coach',
    'orderly': 'Hospital porter',
    'radiographer': 'Radiographer',
    'audiologist': 'Audiologist',
    'dental-tech': 'Dental technician',
    'orthoptist': 'Orthoptist',
    'podiatrist': 'Podiatrist',
    'occupational-therapist': 'Occupational therapist',
    'psychomotor': 'Psychomotor therapist',
    'amp': 'Care support worker',
    'puericultrice': 'Nursery nurse',
    'special-educator': 'Special needs educator',
    'youth-worker': 'Youth worker',
    'school-assistant': 'Teaching assistant',
    'employment-advisor': 'Employment advisor',
    'driving-instructor': 'Driving instructor',
    'lifeguard': 'Lifeguard',
    'life-coach': 'Life coach',
    'prison-officer': 'Prison officer',
    'customs-officer': 'Customs officer',
    'undertaker': 'Funeral director',
    'payroll': 'Payroll administrator',
    'assistant-accountant': 'Assistant accountant',
    'secretary': 'Administrative assistant',
    'medical-secretary': 'Medical secretary',
    'credit-analyst': 'Credit analyst',
    'compliance': 'Compliance manager',
    'order-management': 'Order management / Collections officer',
    'store-manager': 'Store manager',
    'department-head': 'Department head',
    'merchandiser': 'Merchandiser',
    'bookseller': 'Bookseller',
    'tobacconist': 'Tobacconist',
    'wine-merchant': 'Wine merchant',
    'greengrocer': 'Greengrocer',
    'telemarketer': 'Telemarketer',
    'commis-chef': 'Commis chef',
    'kitchen-porter': 'Kitchen porter',
    'sommelier': 'Sommelier',
    'barista': 'Barista',
    'caterer': 'Caterer',
    'housekeeper': 'Housekeeper',
    'concierge': 'Concierge',
    'truck-driver': 'Truck driver',
    'taxi-vtc': 'Taxi / Private hire driver',
    'delivery-rider': 'Delivery rider',
    'warehouse-manager': 'Warehouse manager',
    'crane-operator': 'Crane operator',
    'ship-captain': 'Merchant navy officer',
    'fisherman': 'Fisherman',
    'ticket-inspector': 'Ticket inspector',
    'tiler': 'Tiler',
    'plasterer': 'Plasterer',
    'hvac': 'HVAC technician',
    'glazier': 'Glazier',
    'fiber-tech': 'Telecom / Fiber technician',
    'solar-installer': 'Solar panel installer',
    'car-body': 'Auto body repairer',
    'vehicle-inspector': 'Vehicle inspector',
    'upholsterer': 'Upholsterer',
    'jeweler': 'Jeweler',
    'cobbler': 'Cobbler',
    'logger': 'Logger',
    'farm-worker': 'Farm worker',
    'beekeeper': 'Beekeeper',
    'oenologist': 'Oenologist',
    'dj': 'DJ',
    'stagehand': 'Stage technician',
    'cultural-mediator': 'Cultural mediator',
    'pro-athlete': 'Professional athlete',
    'ski-instructor': 'Ski instructor',
    'animal-keeper': 'Animal keeper',
    'dog-groomer': 'Dog groomer',
  },
  de: {
    'data-entry': 'Dateneingabe-Sachbearbeiter',
    'developer': 'Softwareentwickler',
    'frontend-dev': 'Frontend-Entwickler',
    'backend-dev': 'Backend-Entwickler',
    'fullstack-dev': 'Fullstack-Entwickler',
    'mobile-dev': 'Mobile-Entwickler',
    'devops': 'DevOps Engineer',
    'data-scientist': 'Data Scientist',
    'data-analyst': 'Datenanalyst',
    'data-engineer': 'Data Engineer',
    'ml-engineer': 'Machine Learning Engineer',
    'prompt-engineer': 'Prompt Engineer / KI-Spezialist',
    'cybersecurity': 'Cybersecurity-Experte',
    'qa-tester': 'QA-Tester',
    'it-support': 'IT-Support-Techniker',
    'sysadmin': 'System- & Netzwerkadministrator',
    'cloud-architect': 'Cloud-Architekt',
    'game-developer': 'Spieleentwickler',
    'doctor': 'Allgemeinmediziner',
    'surgeon': 'Chirurg',
    'radiologist': 'Radiologe',
    'anesthetist': 'Anästhesist',
    'dentist': 'Zahnarzt',
    'nurse': 'Krankenpfleger',
    'caregiver': 'Pflegehelfer',
    'midwife': 'Hebamme',
    'physio': 'Physiotherapeut',
    'psychologist': 'Psychologe',
    'psychiatrist': 'Psychiater',
    'pharmacist': 'Apotheker',
    'pharmacy-tech': 'Pharmazeutisch-technischer Assistent',
    'vet': 'Tierarzt',
    'optician': 'Optiker',
    'speech-therapist': 'Logopäde',
    'dietitian': 'Diätassistent / Ernährungsberater',
    'paramedic': 'Rettungssanitäter',
    'social-worker': 'Sozialarbeiter',
    'teacher': 'Lehrer',
    'primary-teacher': 'Grundschullehrer',
    'professor': 'Universitätsprofessor',
    'trainer': 'Weiterbildungstrainer',
    'researcher': 'Forscher / Wissenschaftler',
    'career-advisor': 'Berufsberater',
    'librarian': 'Bibliothekar',
    'graphic-designer': 'Grafikdesigner',
    'ux-designer': 'UX-Designer',
    'ui-designer': 'UI-Designer',
    'motion-designer': 'Motion Designer',
    'illustrator': 'Illustrator',
    'product-designer': 'Produktdesigner',
    'interior-designer': 'Innenarchitekt',
    'architect': 'Architekt',
    'photographer': 'Fotograf',
    'video-editor': 'Videoeditor',
    'writer': 'Redakteur / Journalist',
    'translator': 'Übersetzer / Dolmetscher',
    'screenwriter': 'Drehbuchautor',
    'musician': 'Musiker / Komponist',
    'accountant': 'Buchhalter',
    'chartered-accountant': 'Wirtschaftsprüfer',
    'controller': 'Controller',
    'auditor': 'Auditor',
    'tax-advisor': 'Steuerberater',
    'financial-analyst': 'Finanzanalyst',
    'trader': 'Trader',
    'wealth-manager': 'Vermögensverwalter',
    'actuary': 'Aktuar',
    'lawyer': 'Rechtsanwalt',
    'jurist': 'Unternehmensjurist',
    'notary': 'Notar',
    'magistrate': 'Richter',
    'bank-teller': 'Bankberater',
    'insurer': 'Versicherungsberater',
    'sales': 'Vertriebsmitarbeiter',
    'b2b-sales': 'B2B- / Key-Account-Vertrieb',
    'marketing': 'Marketingleiter',
    'product-marketing': 'Produktmanager',
    'growth-marketer': 'Growth Marketer',
    'seo-specialist': 'SEO- / SEA-Spezialist',
    'social-media': 'Community- / Social-Media-Manager',
    'buyer': 'Einkäufer',
    'ecommerce-manager': 'E-Commerce-Manager',
    'pr': 'Pressesprecher / PR-Referent',
    'shop-assistant': 'Verkäufer',
    'cashier': 'Kassierer',
    'customer-support': 'Kundenberater',
    'manager': 'Manager / Teamleiter',
    'ceo': 'Geschäftsführer / CEO',
    'cfo': 'Kaufmännischer Leiter / CFO',
    'project-manager': 'Projektleiter',
    'product-manager': 'Product Manager',
    'consultant': 'Strategieberater',
    'hr': 'HR-Manager / Personalleiter',
    'recruiter': 'Recruiter',
    'exec-assistant': 'Assistent der Geschäftsführung',
    'entrepreneur': 'Unternehmer',
    'driver': 'Fahrer / Auslieferungsfahrer',
    'factory-worker': 'Produktionsmitarbeiter',
    'logistics': 'Logistikmitarbeiter / Lagerist',
    'maintenance-tech': 'Instandhaltungstechniker',
    'production-engineer': 'Produktionsingenieur',
    'welder': 'Schweißer',
    'cnc-operator': 'CNC-Zerspanungsmechaniker',
    'pilot': 'Verkehrspilot',
    'air-traffic': 'Fluglotse',
    'train-driver': 'Lokführer',
    'site-manager': 'Bauleiter',
    'supply-chain': 'Supply-Chain-Manager',
    'electrician': 'Elektriker',
    'plumber': 'Installateur / Heizungsbauer',
    'carpenter': 'Tischler / Zimmerer',
    'mason': 'Maurer',
    'painter': 'Maler und Lackierer',
    'roofer': 'Dachdecker',
    'chef': 'Koch',
    'baker': 'Bäcker',
    'pastry-chef': 'Konditor',
    'butcher': 'Metzger',
    'hairdresser': 'Friseur',
    'beautician': 'Kosmetiker',
    'mechanic': 'Kfz-Mechaniker',
    'landscaper': 'Landschaftsgärtner / Gärtner',
    'farmer': 'Landwirt',
    'tailor': 'Schneider',
    'police': 'Polizist',
    'firefighter': 'Feuerwehrmann',
    'soldier': 'Soldat',
    'civil-servant': 'Beamter / Verwaltungsangestellter',
    'receptionist': 'Empfangsmitarbeiter',
    'flight-attendant': 'Flugbegleiter',
    'real-estate': 'Immobilienmakler',
    'waiter': 'Kellner',
    'bartender': 'Barkeeper',
    'tour-guide': 'Reiseleiter',
    'sports-coach': 'Sporttrainer',
    'childcare': 'Tagesmutter / Kinderbetreuer',
    'cleaner': 'Reinigungskraft',
    'security-guard': 'Sicherheitsmitarbeiter',
    'comms-manager': 'Kommunikationsmanager',
    'web-writer': 'Webtexter / Content Manager',
    'presenter': 'Moderator',
    'civil-engineer': 'Bauingenieur',
    'mechanical-engineer': 'Maschinenbauingenieur',
    'electrical-engineer': 'Elektroingenieur',
    'chemist': 'Chemiker',
    'biologist': 'Biologe',
    'env-engineer': 'Umweltingenieur',
    'statistician': 'Statistiker',
    'economist': 'Volkswirt',
    'surveyor': 'Vermessungsingenieur',
    'urban-planner': 'Stadtplaner',
    'lab-technician': 'Labortechniker',
    'meteorologist': 'Meteorologe',
    'dpo': 'Datenschutzbeauftragter (DSB)',
    'actor': 'Schauspieler',
    'dancer': 'Tänzer',
    'sound-engineer': 'Tontechniker',
    'film-director': 'Regisseur / Produzent',
    'event-manager': 'Eventmanager',
    'makeup-artist': 'Make-up-Artist',
    'bus-driver': 'Busfahrer',
    'postal-worker': 'Postbote',
    'waste-collector': 'Müllwerker',
    'travel-agent': 'Reiseverkehrskaufmann',
    'florist': 'Florist',
    'watchmaker': 'Uhrmacher',
    'locksmith': 'Schlosser',
    'mover': 'Möbelpacker',
    'fishmonger': 'Fischhändler',
    'scrum-master': 'Scrum Master / Agile Coach',
    'orderly': 'Krankentransporter',
    'radiographer': 'Radiologietechnologe',
    'audiologist': 'Hörakustiker',
    'dental-tech': 'Zahntechniker',
    'orthoptist': 'Orthoptist',
    'podiatrist': 'Podologe',
    'occupational-therapist': 'Ergotherapeut',
    'psychomotor': 'Psychomotoriktherapeut',
    'amp': 'Sozialbetreuer',
    'puericultrice': 'Kinderpflegerin',
    'special-educator': 'Heilpädagoge',
    'youth-worker': 'Sozialpädagoge',
    'school-assistant': 'Schulbegleiter',
    'employment-advisor': 'Arbeitsvermittler',
    'driving-instructor': 'Fahrlehrer',
    'lifeguard': 'Rettungsschwimmer',
    'life-coach': 'Coach',
    'prison-officer': 'Justizvollzugsbeamter',
    'customs-officer': 'Zollbeamter',
    'undertaker': 'Bestatter',
    'payroll': 'Lohnbuchhalter',
    'assistant-accountant': 'Buchhaltungsassistent',
    'secretary': 'Verwaltungsassistent',
    'medical-secretary': 'Arztsekretär',
    'credit-analyst': 'Kreditanalyst',
    'compliance': 'Compliance-Manager',
    'order-management': 'Sachbearbeiter Auftragsabwicklung',
    'store-manager': 'Filialleiter',
    'department-head': 'Abteilungsleiter',
    'merchandiser': 'Merchandiser',
    'bookseller': 'Buchhändler',
    'tobacconist': 'Tabakhändler',
    'wine-merchant': 'Weinhändler',
    'greengrocer': 'Obst- und Gemüsehändler',
    'telemarketer': 'Telefonverkäufer',
    'commis-chef': 'Jungkoch',
    'kitchen-porter': 'Küchenhilfe',
    'sommelier': 'Sommelier',
    'barista': 'Barista',
    'caterer': 'Caterer',
    'housekeeper': 'Zimmermädchen / Hausdame',
    'concierge': 'Concierge / Hausmeister',
    'truck-driver': 'Lkw-Fahrer',
    'taxi-vtc': 'Taxi- / Mietwagenfahrer',
    'delivery-rider': 'Fahrradkurier',
    'warehouse-manager': 'Lagerleiter',
    'crane-operator': 'Kranführer',
    'ship-captain': 'Nautischer Offizier',
    'fisherman': 'Fischer',
    'ticket-inspector': 'Fahrkartenkontrolleur',
    'tiler': 'Fliesenleger',
    'plasterer': 'Trockenbauer',
    'hvac': 'Kältetechniker',
    'glazier': 'Glaser',
    'fiber-tech': 'Telekommunikationstechniker',
    'solar-installer': 'Solaranlagen-Installateur',
    'car-body': 'Karosseriebauer',
    'vehicle-inspector': 'Kfz-Prüfer',
    'upholsterer': 'Polsterer',
    'jeweler': 'Juwelier',
    'cobbler': 'Schuhmacher',
    'logger': 'Waldarbeiter',
    'farm-worker': 'Landarbeiter',
    'beekeeper': 'Imker',
    'oenologist': 'Önologe',
    'dj': 'DJ',
    'stagehand': 'Veranstaltungstechniker',
    'cultural-mediator': 'Kulturvermittler',
    'pro-athlete': 'Profisportler',
    'ski-instructor': 'Skilehrer',
    'animal-keeper': 'Tierpfleger',
    'dog-groomer': 'Hundefriseur',
  },
  es: {
    'data-entry': 'Operador de entrada de datos',
    'developer': 'Desarrollador de software',
    'frontend-dev': 'Desarrollador front-end',
    'backend-dev': 'Desarrollador back-end',
    'fullstack-dev': 'Desarrollador full-stack',
    'mobile-dev': 'Desarrollador móvil',
    'devops': 'Ingeniero DevOps',
    'data-scientist': 'Data Scientist',
    'data-analyst': 'Analista de datos',
    'data-engineer': 'Data Engineer',
    'ml-engineer': 'Ingeniero de Machine Learning',
    'prompt-engineer': 'Prompt Engineer / Especialista en IA',
    'cybersecurity': 'Experto en ciberseguridad',
    'qa-tester': 'Tester QA',
    'it-support': 'Técnico de soporte informático',
    'sysadmin': 'Administrador de sistemas y redes',
    'cloud-architect': 'Arquitecto cloud',
    'game-developer': 'Desarrollador de videojuegos',
    'doctor': 'Médico de familia',
    'surgeon': 'Cirujano',
    'radiologist': 'Radiólogo',
    'anesthetist': 'Anestesista',
    'dentist': 'Dentista',
    'nurse': 'Enfermero',
    'caregiver': 'Auxiliar de enfermería',
    'midwife': 'Matrona',
    'physio': 'Fisioterapeuta',
    'psychologist': 'Psicólogo',
    'psychiatrist': 'Psiquiatra',
    'pharmacist': 'Farmacéutico',
    'pharmacy-tech': 'Técnico de farmacia',
    'vet': 'Veterinario',
    'optician': 'Óptico',
    'speech-therapist': 'Logopeda',
    'dietitian': 'Dietista / Nutricionista',
    'paramedic': 'Técnico en emergencias sanitarias',
    'social-worker': 'Trabajador social',
    'teacher': 'Profesor',
    'primary-teacher': 'Maestro de primaria',
    'professor': 'Profesor universitario',
    'trainer': 'Formador profesional',
    'researcher': 'Investigador / Científico',
    'career-advisor': 'Orientador profesional',
    'librarian': 'Bibliotecario',
    'graphic-designer': 'Diseñador gráfico',
    'ux-designer': 'Diseñador UX',
    'ui-designer': 'Diseñador UI',
    'motion-designer': 'Motion Designer',
    'illustrator': 'Ilustrador',
    'product-designer': 'Diseñador de producto',
    'interior-designer': 'Diseñador de interiores',
    'architect': 'Arquitecto',
    'photographer': 'Fotógrafo',
    'video-editor': 'Editor de vídeo',
    'writer': 'Redactor / Periodista',
    'translator': 'Traductor / Intérprete',
    'screenwriter': 'Guionista',
    'musician': 'Músico / Compositor',
    'accountant': 'Contable',
    'chartered-accountant': 'Censor jurado de cuentas',
    'controller': 'Controller de gestión',
    'auditor': 'Auditor',
    'tax-advisor': 'Asesor fiscal',
    'financial-analyst': 'Analista financiero',
    'trader': 'Trader',
    'wealth-manager': 'Gestor de patrimonio',
    'actuary': 'Actuario',
    'lawyer': 'Abogado',
    'jurist': 'Asesor jurídico de empresa',
    'notary': 'Notario',
    'magistrate': 'Magistrado / Juez',
    'bank-teller': 'Asesor bancario',
    'insurer': 'Agente de seguros',
    'sales': 'Comercial',
    'b2b-sales': 'Comercial B2B / Grandes cuentas',
    'marketing': 'Responsable de marketing',
    'product-marketing': 'Product Manager',
    'growth-marketer': 'Growth Marketer',
    'seo-specialist': 'Especialista SEO / SEA',
    'social-media': 'Community / Social Media Manager',
    'buyer': 'Comprador',
    'ecommerce-manager': 'Responsable de e-commerce',
    'pr': 'Responsable de prensa / Relaciones públicas',
    'shop-assistant': 'Dependiente',
    'cashier': 'Cajero',
    'customer-support': 'Asesor de atención al cliente',
    'manager': 'Manager / Jefe de equipo',
    'ceo': 'Director general / CEO',
    'cfo': 'Director administrativo y financiero',
    'project-manager': 'Jefe de proyecto',
    'product-manager': 'Product Manager',
    'consultant': 'Consultor de estrategia',
    'hr': 'Responsable de RR. HH.',
    'recruiter': 'Reclutador / Técnico de selección',
    'exec-assistant': 'Asistente de dirección',
    'entrepreneur': 'Emprendedor',
    'driver': 'Conductor / Repartidor',
    'factory-worker': 'Operario de producción',
    'logistics': 'Operario logístico / Mozo de almacén',
    'maintenance-tech': 'Técnico de mantenimiento',
    'production-engineer': 'Ingeniero de producción',
    'welder': 'Soldador',
    'cnc-operator': 'Operador CNC',
    'pilot': 'Piloto de aerolínea',
    'air-traffic': 'Controlador aéreo',
    'train-driver': 'Maquinista de tren',
    'site-manager': 'Jefe de obra',
    'supply-chain': 'Responsable de cadena de suministro',
    'electrician': 'Electricista',
    'plumber': 'Fontanero / Calefactor',
    'carpenter': 'Carpintero',
    'mason': 'Albañil',
    'painter': 'Pintor de obra',
    'roofer': 'Techador',
    'chef': 'Cocinero / Chef',
    'baker': 'Panadero',
    'pastry-chef': 'Pastelero',
    'butcher': 'Carnicero',
    'hairdresser': 'Peluquero',
    'beautician': 'Esteticista',
    'mechanic': 'Mecánico de automóviles',
    'landscaper': 'Paisajista / Jardinero',
    'farmer': 'Agricultor',
    'tailor': 'Sastre / Modista',
    'police': 'Policía',
    'firefighter': 'Bombero',
    'soldier': 'Militar',
    'civil-servant': 'Funcionario / Auxiliar administrativo',
    'receptionist': 'Recepcionista',
    'flight-attendant': 'Auxiliar de vuelo',
    'real-estate': 'Agente inmobiliario',
    'waiter': 'Camarero',
    'bartender': 'Barman',
    'tour-guide': 'Guía turístico',
    'sports-coach': 'Entrenador deportivo',
    'childcare': 'Auxiliar de guardería / Cuidador infantil',
    'cleaner': 'Personal de limpieza',
    'security-guard': 'Vigilante de seguridad',
    'comms-manager': 'Responsable de comunicación',
    'web-writer': 'Redactor web / Content manager',
    'presenter': 'Presentador',
    'civil-engineer': 'Ingeniero civil',
    'mechanical-engineer': 'Ingeniero mecánico',
    'electrical-engineer': 'Ingeniero eléctrico',
    'chemist': 'Químico',
    'biologist': 'Biólogo',
    'env-engineer': 'Ingeniero ambiental',
    'statistician': 'Estadístico',
    'economist': 'Economista',
    'surveyor': 'Topógrafo',
    'urban-planner': 'Urbanista',
    'lab-technician': 'Técnico de laboratorio',
    'meteorologist': 'Meteorólogo',
    'dpo': 'Delegado de protección de datos (DPO)',
    'actor': 'Actor',
    'dancer': 'Bailarín',
    'sound-engineer': 'Ingeniero de sonido',
    'film-director': 'Director de cine / Productor',
    'event-manager': 'Responsable de eventos',
    'makeup-artist': 'Maquillador profesional',
    'bus-driver': 'Conductor de autobús',
    'postal-worker': 'Cartero',
    'waste-collector': 'Basurero',
    'travel-agent': 'Agente de viajes',
    'florist': 'Florista',
    'watchmaker': 'Relojero',
    'locksmith': 'Cerrajero',
    'mover': 'Mozo de mudanzas',
    'fishmonger': 'Pescadero',
    'scrum-master': 'Scrum Master / Agile Coach',
    'orderly': 'Camillero',
    'radiographer': 'Técnico en radiología',
    'audiologist': 'Audioprotesista',
    'dental-tech': 'Protésico dental',
    'orthoptist': 'Ortoptista',
    'podiatrist': 'Podólogo',
    'occupational-therapist': 'Terapeuta ocupacional',
    'psychomotor': 'Psicomotricista',
    'amp': 'Auxiliar de educación y apoyo social',
    'puericultrice': 'Auxiliar de puericultura',
    'special-educator': 'Educador especializado',
    'youth-worker': 'Animador sociocultural',
    'school-assistant': 'Auxiliar educativo',
    'employment-advisor': 'Asesor de empleo',
    'driving-instructor': 'Profesor de autoescuela',
    'lifeguard': 'Socorrista',
    'life-coach': 'Coach',
    'prison-officer': 'Funcionario de prisiones',
    'customs-officer': 'Agente de aduanas',
    'undertaker': 'Asesor funerario',
    'payroll': 'Gestor de nóminas',
    'assistant-accountant': 'Auxiliar contable',
    'secretary': 'Asistente administrativo',
    'medical-secretary': 'Secretario médico',
    'credit-analyst': 'Analista de crédito',
    'compliance': 'Responsable de cumplimiento',
    'order-management': 'Gestor de pedidos y cobros',
    'store-manager': 'Encargado de tienda',
    'department-head': 'Jefe de sección',
    'merchandiser': 'Merchandiser',
    'bookseller': 'Librero',
    'tobacconist': 'Estanquero',
    'wine-merchant': 'Bodeguero',
    'greengrocer': 'Frutero',
    'telemarketer': 'Teleoperador',
    'commis-chef': 'Ayudante de cocina',
    'kitchen-porter': 'Lavaplatos',
    'sommelier': 'Sumiller',
    'barista': 'Barista',
    'caterer': 'Servicio de catering',
    'housekeeper': 'Camarero de piso / Gobernanta',
    'concierge': 'Conserje',
    'truck-driver': 'Camionero',
    'taxi-vtc': 'Conductor de VTC / Taxi',
    'delivery-rider': 'Repartidor',
    'warehouse-manager': 'Responsable de almacén',
    'crane-operator': 'Operador de grúa',
    'ship-captain': 'Oficial de la marina mercante',
    'fisherman': 'Pescador',
    'ticket-inspector': 'Revisor',
    'tiler': 'Alicatador',
    'plasterer': 'Escayolista',
    'hvac': 'Técnico frigorista',
    'glazier': 'Cristalero',
    'fiber-tech': 'Técnico de telecomunicaciones',
    'solar-installer': 'Instalador de paneles solares',
    'car-body': 'Chapista',
    'vehicle-inspector': 'Inspector técnico de vehículos',
    'upholsterer': 'Tapicero',
    'jeweler': 'Joyero',
    'cobbler': 'Zapatero',
    'logger': 'Leñador',
    'farm-worker': 'Peón agrícola',
    'beekeeper': 'Apicultor',
    'oenologist': 'Enólogo',
    'dj': 'DJ',
    'stagehand': 'Técnico de espectáculos',
    'cultural-mediator': 'Mediador cultural',
    'pro-athlete': 'Deportista profesional',
    'ski-instructor': 'Monitor de esquí',
    'animal-keeper': 'Cuidador de animales',
    'dog-groomer': 'Peluquero canino',
  },
  zh: {
    'data-entry': '数据录入员',
    'developer': '软件开发工程师',
    'frontend-dev': '前端开发工程师',
    'backend-dev': '后端开发工程师',
    'fullstack-dev': '全栈开发工程师',
    'mobile-dev': '移动端开发工程师',
    'devops': 'DevOps 工程师',
    'data-scientist': '数据科学家',
    'data-analyst': '数据分析师',
    'data-engineer': '数据工程师',
    'ml-engineer': '机器学习工程师',
    'prompt-engineer': '提示词工程师 / AI 专家',
    'cybersecurity': '网络安全专家',
    'qa-tester': 'QA 测试工程师',
    'it-support': 'IT 支持技术员',
    'sysadmin': '系统与网络管理员',
    'cloud-architect': '云架构师',
    'game-developer': '游戏开发工程师',
    'doctor': '全科医生',
    'surgeon': '外科医生',
    'radiologist': '放射科医生',
    'anesthetist': '麻醉师',
    'dentist': '牙医',
    'nurse': '护士',
    'caregiver': '护理员',
    'midwife': '助产士',
    'physio': '物理治疗师',
    'psychologist': '心理学家',
    'psychiatrist': '精神科医生',
    'pharmacist': '药剂师',
    'pharmacy-tech': '药剂技术员',
    'vet': '兽医',
    'optician': '配镜师',
    'speech-therapist': '言语治疗师',
    'dietitian': '营养师',
    'paramedic': '急救员',
    'social-worker': '社会工作者',
    'teacher': '教师',
    'primary-teacher': '小学教师',
    'professor': '大学教授',
    'trainer': '职业培训师',
    'researcher': '研究员 / 科学家',
    'career-advisor': '职业顾问',
    'librarian': '图书馆员',
    'graphic-designer': '平面设计师',
    'ux-designer': 'UX 设计师',
    'ui-designer': 'UI 设计师',
    'motion-designer': '动效设计师',
    'illustrator': '插画师',
    'product-designer': '产品设计师',
    'interior-designer': '室内设计师',
    'architect': '建筑师',
    'photographer': '摄影师',
    'video-editor': '视频剪辑师',
    'writer': '撰稿人 / 记者',
    'translator': '翻译 / 口译员',
    'screenwriter': '编剧',
    'musician': '音乐家 / 作曲家',
    'accountant': '会计',
    'chartered-accountant': '注册会计师',
    'controller': '管理会计 / 财务控制',
    'auditor': '审计师',
    'tax-advisor': '税务顾问',
    'financial-analyst': '财务分析师',
    'trader': '交易员',
    'wealth-manager': '财富管理师',
    'actuary': '精算师',
    'lawyer': '律师',
    'jurist': '企业法务',
    'notary': '公证员',
    'magistrate': '法官',
    'bank-teller': '银行客户经理',
    'insurer': '保险顾问',
    'sales': '销售代表',
    'b2b-sales': 'B2B / 大客户销售',
    'marketing': '市场营销经理',
    'product-marketing': '产品经理',
    'growth-marketer': '增长营销专家',
    'seo-specialist': 'SEO / SEA 专员',
    'social-media': '社群 / 社交媒体经理',
    'buyer': '采购员',
    'ecommerce-manager': '电商运营经理',
    'pr': '公关专员',
    'shop-assistant': '店员',
    'cashier': '收银员',
    'customer-support': '客户服务专员',
    'manager': '经理／团队主管',
    'ceo': '首席执行官',
    'cfo': '财务总监',
    'project-manager': '项目经理',
    'product-manager': '产品经理',
    'consultant': '战略顾问',
    'hr': '人力资源经理',
    'recruiter': '招聘专员',
    'exec-assistant': '行政助理',
    'entrepreneur': '创业者',
    'driver': '司机／配送员',
    'factory-worker': '生产操作员',
    'logistics': '物流／仓储管理员',
    'maintenance-tech': '维修技术员',
    'production-engineer': '生产工程师',
    'welder': '焊工',
    'cnc-operator': '数控机床操作员',
    'pilot': '民航飞行员',
    'air-traffic': '空中交通管制员',
    'train-driver': '火车司机',
    'site-manager': '工地负责人',
    'supply-chain': '供应链经理',
    'electrician': '电工',
    'plumber': '管道／供暖工',
    'carpenter': '木工',
    'mason': '泥瓦工',
    'painter': '油漆工',
    'roofer': '屋顶工',
    'chef': '厨师',
    'baker': '面包师',
    'pastry-chef': '糕点师',
    'butcher': '肉类加工师',
    'hairdresser': '理发师',
    'beautician': '美容师',
    'mechanic': '汽车修理工',
    'landscaper': '景观园艺师',
    'farmer': '农民',
    'tailor': '裁缝',
    'police': '警察',
    'firefighter': '消防员',
    'soldier': '军人',
    'civil-servant': '公务员',
    'receptionist': '前台接待员',
    'flight-attendant': '空乘人员',
    'real-estate': '房地产经纪人',
    'waiter': '服务员',
    'bartender': '调酒师',
    'tour-guide': '导游',
    'sports-coach': '体育教练',
    'childcare': '幼儿保育员',
    'cleaner': '保洁员',
    'security-guard': '保安',
    'comms-manager': '传播专员',
    'web-writer': '网络内容撰稿人／内容经理',
    'presenter': '主持人',
    'civil-engineer': '土木工程师',
    'mechanical-engineer': '机械工程师',
    'electrical-engineer': '电气工程师',
    'chemist': '化学家',
    'biologist': '生物学家',
    'env-engineer': '环境工程师',
    'statistician': '统计师',
    'economist': '经济学家',
    'surveyor': '测量工程师',
    'urban-planner': '城市规划师',
    'lab-technician': '实验室技术员',
    'meteorologist': '气象学家',
    'dpo': '数据保护官（DPO）',
    'actor': '演员',
    'dancer': '舞蹈演员',
    'sound-engineer': '音响工程师',
    'film-director': '导演／制片人',
    'event-manager': '活动策划经理',
    'makeup-artist': '专业化妆师',
    'bus-driver': '公交车司机',
    'postal-worker': '邮递员',
    'waste-collector': '环卫工人',
    'travel-agent': '旅行社代理',
    'florist': '花艺师',
    'watchmaker': '钟表匠',
    'locksmith': '锁匠',
    'mover': '搬运工',
    'fishmonger': '鱼贩',
    'scrum-master': '敏捷教练',
    'orderly': '护工',
    'radiographer': '放射技师',
    'audiologist': '助听器验配师',
    'dental-tech': '牙科技师',
    'orthoptist': '视轴矫正师',
    'podiatrist': '足病治疗师',
    'occupational-therapist': '职业治疗师',
    'psychomotor': '精神运动治疗师',
    'amp': '社会教育辅助员',
    'puericultrice': '育婴护理员',
    'special-educator': '特殊教育工作者',
    'youth-worker': '青少年社工',
    'school-assistant': '随班辅助员',
    'employment-advisor': '就业顾问',
    'driving-instructor': '驾驶教练',
    'lifeguard': '救生员',
    'life-coach': '生活教练',
    'prison-officer': '监狱看守',
    'customs-officer': '海关关员',
    'undertaker': '殡葬顾问',
    'payroll': '薪资专员',
    'assistant-accountant': '会计助理',
    'secretary': '行政助理',
    'medical-secretary': '医务秘书',
    'credit-analyst': '信贷分析师',
    'compliance': '合规经理',
    'order-management': '订单管理专员',
    'store-manager': '店长',
    'department-head': '部门主管',
    'merchandiser': '陈列师',
    'bookseller': '书商',
    'tobacconist': '烟草店店主',
    'wine-merchant': '葡萄酒商',
    'greengrocer': '果蔬商',
    'telemarketer': '电话销售员',
    'commis-chef': '厨房帮工',
    'kitchen-porter': '洗碗工',
    'sommelier': '侍酒师',
    'barista': '咖啡师',
    'caterer': '餐饮承办员',
    'housekeeper': '客房服务员',
    'concierge': '门房',
    'truck-driver': '货车司机',
    'taxi-vtc': '网约车/出租车司机',
    'delivery-rider': '配送骑手',
    'warehouse-manager': '仓库主管',
    'crane-operator': '起重机操作员',
    'ship-captain': '商船船员',
    'fisherman': '渔民',
    'ticket-inspector': '检票员',
    'tiler': '瓷砖工',
    'plasterer': '石膏板工',
    'hvac': '制冷技师',
    'glazier': '玻璃安装工',
    'fiber-tech': '电信/光纤技师',
    'solar-installer': '太阳能板安装工',
    'car-body': '汽车钣金喷漆工',
    'vehicle-inspector': '车辆检测员',
    'upholsterer': '软装饰工',
    'jeweler': '珠宝匠',
    'cobbler': '修鞋匠',
    'logger': '伐木工',
    'farm-worker': '农业工人',
    'beekeeper': '养蜂人',
    'oenologist': '酿酒师',
    'dj': 'DJ',
    'stagehand': '舞台技师',
    'cultural-mediator': '文化协调员',
    'pro-athlete': '职业运动员',
    'ski-instructor': '滑雪教练',
    'animal-keeper': '动物饲养员',
    'dog-groomer': '宠物美容师',
  },
}
